@baseUrl = https://linkup-eta.vercel.app/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoiemVuZGEud2Vic2l0ZXNAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImlzQXBwbGljYW50Ijp0cnVlLCJpYXQiOjE3NDA5MTQ1NjIsImV4cCI6MTc0MDkxODE2Mn0.voTiH3V00ghhDrdx1VgC1F2MDEx_lg9UlV9ITv6N4MU

http://localhost:3000

### Submit application
POST {{baseUrl}}/apply
Content-Type: application/json

{
  "firstName": "turca",
  "lastName": "said",
  "email": "h@gmail.com",
  "password": "securepassword123",
  "linkedinProfile": "https://www.linkedin.com/in/johndoe",
  "startupName": "TechInnovate",
  "shortDescription": "AI-powered sustainability solutions",
  "problemSolved": "We're addressing climate change through innovative AI technologies.",
  "sector": "CleanTech",
  "stage": "mvp",
  "hasInvestment": false,
  "seekingInvestment": true,
  "hasCustomers": false,
  "customersDetails": "",
  "links": "https://techinnovate.com",
  "founderContact": "John Doe, johndoe@techinnovate.com",
  "whyJoinLinkUp": "We believe LinkUp can provide the mentorship and resources we need to scale our impact.",
  "howHeardAboutLinkUp": "Through a recommendation from a fellow entrepreneur."
}

### Get all applications (Admin only)
GET {{baseUrl}}/admin/applications
Authorization: Bearer {{token}}

### Regular User Login
# @name userLogin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email":"zenda.websites@gmail.com",
  "password":"123"
}

### Update application status (Admin only)
PUT {{baseUrl}}/admin/applications/32
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "accepted"
}


### Get user progress
GET {{baseUrl}}/progress/1
Authorization: Bearer {{token}}

### Get user progress for a specific module
GET {{baseUrl}}/progress/1/1
Authorization: Bearer {{token}}

### Update user progress for a specific module
PUT {{baseUrl}}/progress/1/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "progress": 75,
  "currentModule": 1,
  "completedModules": [1]
}

### Get dashboard data
GET {{baseUrl}}/dashboard
Authorization: Bearer {{token}}

### Update dashboard progress
POST {{baseUrl}}/dashboard/update-progress
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "moduleId": 1,
  "progress": 50
}

